server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlite:/Users/luciozhang/wepay/java-server/mch_transfer_api_demo/src/main/resources/db.sqlite # 创建的sqlite数据库所在路径
    type: org.sqlite.SQLiteDataSource
# mybatis配置
mybatis:
  mapper-locations: classpath*:mybatis/*.xml # 配置mapper.xml文件路径
  type-aliases-package: transfer.domain.entity # 实体类包名